options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/cache-assessment/cache-assessment-app/cache-assessment-app:$SHORT_SHA-$_ENV', './app']

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/cache-assessment/cache-assessment-app/cache-assessment-app:$SHORT_SHA-$_ENV']

  # Step 3: Deploy to GKE using kubectl and kustomize
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials $_CLUSTER_NAME --region=$_CLUSTER_REGION
        export SHORT_SHA=$(git rev-parse --short HEAD)
        sed -i "s|newTag:.*|newTag: ${SHORT_SHA}-${_ENV}|" k8s/overlays/${_ENV}/kustomization.yaml
        kubectl apply -f k8s/base/namespace.yaml
        kubectl kustomize k8s/overlays/${_ENV} | kubectl apply -f -

        # Fix eso-ksa namespace
        kubectl get sa ${_ENV}-eso-ksa -n cache-${_ENV} -o yaml | \
        sed 's/namespace: cache-${_ENV}/namespace: external-secrets/' | \
        kubectl apply -f -



substitutions:
  _CLUSTER_NAME: 'cache-assessment-cluster'
  _CLUSTER_REGION: 'us-east1'
  _ENV: 'staging'

timeout: '900s'