apiVersion: v1
kind: ServiceAccount
metadata:
  name: cache-ksa
  annotations:
    iam.gke.io/gcp-service-account: cache-app@martin-sandbox-272210.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-ksa
  namespace: external-secrets
  annotations:
    iam.gke.io/gcp-service-account: eso-gcp@martin-sandbox-272210.iam.gserviceaccount.com
