apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secrets
  namespace: cache-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secretstore
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: staging-db-password
    - secretKey: DB_USER
      remoteRef:
        key: staging-db-user
