project_id   = "cache-assessment"
region       = "us-east1"
staging_db_user      = "staging_cache_user"
staging_db_name      = "staging_cache_db"
prod_db_user      = "prod_cache_user"
prod_db_name      = "prod_cache_db"
