---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-assessment-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cache-assessment-app
  template:
    metadata:
      labels:
        app: cache-assessment-app
    spec:
      serviceAccountName: placeholder-sa
      containers:
        - name: cache-assessment-app
          image: 'martinkaburu/cache-assessment-app:latest'
          ports:
            - containerPort: 8080
          env:
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: PROJECT_ID
              value: cache-assessment
            - name: PUBSUB_TOPIC
              value: projects/cache-assessment/topics/cache-assessment-topic
