apiVersion: v1
kind: ServiceAccount
metadata:
  name: cache-ksa
  annotations:
    iam.gke.io/gcp-service-account: cache-gsa@cache-assessment.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-ksa
  namespace: external-secrets
  annotations:
    iam.gke.io/gcp-service-account: eso-gsa@cache-assessment.iam.gserviceaccount.com
