apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cache-staging
namePrefix: staging-

resources:
- ../../base

images:
- name: martinkaburu/cache-assessment-app
  newName: us-east1-docker.pkg.dev/cache-assessment/cache-assessment-app/cache-assessment-app
  newTag: 2914fbb-staging

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/serviceAccountName
      value: staging-cache-ksa
    - op: replace
      path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
      value: staging-db-secrets
    - op: replace
      path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name
      value: staging-db-secrets
  target:
    kind: Deployment
    name: staging-cache-assessment-app
- path: patch-eso-ksa-ns.yaml

