apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cache-staging
namespaceOverride: true

namePrefix: staging-

resources:
- ../../base

images:
- name: martinkaburu/cache-assessment-app
  newName: us-east1-docker.pkg.dev/cache-assessment/cache-assessment-app/cache-assessment-app
  newTag: placeholder

patches:
- target:
    kind: Deployment
    name: cache-assessment-app
  patch: |-
    - op: replace
      path: /spec/template/spec/serviceAccountName
      value: staging-cache-ksa
    
    - op: replace
      path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name
      value: staging-db-secrets
